return {
  'folke/which-key.nvim',
  event = 'VeryLazy',
  opts = {
    preset = 'helix',
    spec = {
      { '<leader>c', group = '[C]ode' },
      { '<leader>c_', hidden = true },
      { '<leader>d', group = '[D]ocument' },
      { '<leader>d_', hidden = true },
      { '<leader>e', group = 's[E]lect' },
      { '<leader>e_', hidden = true },
      { '<leader>g', group = '[G]it' },
      { '<leader>g_', hidden = true },
      { '<leader>h', group = 'Git [H]unk' },
      { '<leader>h_', hidden = true },
      { '<leader>m', group = '[M]ove' },
      { '<leader>m_', hidden = true },
      { '<leader>o', group = 'c[O]mpetitive' },
      { '<leader>o_', hidden = true },
      { '<leader>r', group = '[R]ename' },
      { '<leader>r_', hidden = true },
      { '<leader>s', group = '[S]earch' },
      { '<leader>s_', hidden = true },
      { '<leader>t', group = '[T]oggle' },
      { '<leader>t_', hidden = true },
      { '<leader>u', group = 's[U]bstitute' },
      { '<leader>u_', hidden = true },
      { '<leader>w', group = '[W]orkspace' },
      { '<leader>w_', hidden = true },
      { '<leader>y', group = '[Y]ank' },
      { '<leader>y_', hidden = true },
      { '<leader>x', group = 'File e[X]plorer' },
      { '<leader>x_', hidden = true },
      { '<leader>h', group = 'Git [H]unk', mode = { 'v' } },
    },
  },
}
